name: Maven Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version: [11, 17]

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK (required for Maven), with Java version matrix
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java-version }}

      # Cache Maven dependencies to speed up subsequent builds
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ matrix.java-version }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build the project
      - name: Build project
        run: mvn clean compile

      # Run tests
      - name: Run tests
        run: mvn test

      # Package the application
      - name: Package application
        run: mvn package

      # Upload the packaged artifact for downstream use
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: target/*.jar
          name: maven-build-${{ matrix.java-version }}

